[package]
name = "derive_commands"
version = "0.1.0"
authors = ["iandwelker <iandwelker@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.72"
quote = "1.0"
proc-macro2 = "1.0"
